theme: jekyll-theme-minimal
title: Aashraya Sachdeva
description: Director of Engineering, AI Agents | Engineering Leader & AI Expert
author: Aashraya Sachdeva
email: hello@aashsach.me
plugins:
  - jekyll-feed
  - jekyll-seo-tag
